server:
  port: 8088
spring:
  application:
    name: auth-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///yun

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ly:
  jwt:
        secret: ly@Login(Auth}*^31)&heiMa31%f3q2 # 登录校验的密钥
        pubKeyPath: F:\\tmp\\rsa\\rsa.pub # 公钥地址
        priKeyPath: F:\\tmp\\rsa\\rsa.pri # 私钥地址
        expire: 30 # 过期时间,单位分钟
        cookieName: LY_TOKEN