server:
  port: 8084
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.52.128:9300
  jackson:
    default-property-inclusion:  non_null
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.52.128
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
